org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showShortLogName=true
org.slf4j.simpleLogger.log.org.deepsymmetry=warn
# newer CDJ-3000 firmware sends longer status packets than beat-link expects: harmless
org.slf4j.simpleLogger.log.org.deepsymmetry.beatlink.CdjStatus=error
