-- ShowBuilder job (patch), generated by ma3-showcreator. Do not edit; recompile instead.
return {
  format = "ma3sc-job",
  version = 1,
  kind = "patch",
  job_id = "JOB_ID",
  ma3_version = "2.3.2",
  profile = "2.3",
  strict_version = true,
  log_file = "log_patch.jsonl",
  export_prefix = "export_patch_",
  steps = {
    {
      op = "patch",
      fixtures = "Fixture 1 Thru 9999",
      props = {
        "FID",
        "CID",
        "Name",
        "PosX",
        "PosY",
        "PosZ",
        "RotX",
        "RotY",
        "RotZ",
        "Layer",
        "Class",
      },
    },
  },
}
