-- ShowBuilder job (inspect), generated by ma3-showcreator. Do not edit; recompile instead.
return {
  format = "ma3sc-job",
  version = 1,
  kind = "inspect",
  job_id = "JOB_ID",
  ma3_version = "2.3.2",
  profile = "2.3",
  strict_version = true,
  log_file = "log_inspect.jsonl",
  export_prefix = "export_inspect_",
  steps = {
    {
      op = "paths",
    },
    {
      op = "cmd",
      cmd = "ShowCreatorSyntaxProbe",
      fatal = false,
      allow_fail = true,
      note = "deliberately invalid: logs the error feedback text",
    },
    {
      op = "list",
      addr = "Group 501 Thru 599",
    },
    {
      op = "list",
      addr = "Sequence 501 Thru 599",
    },
    {
      op = "list",
      addr = "MAtricks 501 Thru 599",
    },
    {
      op = "list",
      addr = "Preset 21.1 Thru 21.200",
    },
    {
      op = "list",
      addr = "Fixture 1 Thru 9999",
      note = "last: riskiest address",
    },
  },
}
