package automa3.show;

import com.fasterxml.jackson.databind.JsonNode;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The planner's brief: one compact markdown file with everything the planner needs to decide, generated
 * deterministically from the settings, rig.json, library.json and the AutoMA3 look list.
 */
final class Brief {

    static final String NAME_FORBIDDEN = "\\ \" $ & * ? , . ; ^ { | } ~";

    private Brief() {
    }

    private static JsonNode ma3(JsonNode look) {
        com.fasterxml.jackson.databind.node.ObjectNode m = look.path("ma3").isObject()
                ? ((com.fasterxml.jackson.databind.node.ObjectNode) look.get("ma3")).deepCopy() : ShowFiles.object();
        for (String k : List.of("page", "exec", "sequence")) if (look.has(k) && !m.has(k)) m.set(k, look.get(k));
        return m;
    }

    private static String energy(JsonNode look) {
        JsonNode e = look.path("energy").isObject() ? look.get("energy") : ShowFiles.object();
        JsonNode lo = e.has("min") ? e.get("min") : look.has("energyMin") ? look.get("energyMin") : ShowFiles.JSON.getNodeFactory().numberNode(0);
        JsonNode hi = e.has("max") ? e.get("max") : look.has("energyMax") ? look.get("energyMax") : ShowFiles.JSON.getNodeFactory().numberNode(1);
        return Py.g(lo) + "–" + Py.g(hi);
    }

    private static String orDash(String s) {
        return s == null || s.isEmpty() ? "-" : s;
    }

    static String build(String show, ShowSettings s, JsonNode rig, JsonNode library, List<JsonNode> looks, String looksSource) {
        JsonNode fixtures = rig.get("fixtures");
        Set<String> capsPresent = new HashSet<>();
        for (JsonNode f : fixtures) capsPresent.addAll(ShowFiles.texts(f.get("caps")));
        List<String> out = new ArrayList<>();

        out.add("# Planning brief: " + show);
        out.add("Generated by AutoMA3 (`./sc brief`). Do not edit; regenerate after changing inputs.\n");
        out.add("**Write the plan to:** `shows/" + show + "/plan.json` (relative to the AutoMA3 data folder; `../shows/"
                + show + "/plan.json` from the planner folder)\n");

        out.add("## Limits");
        out.add("- Groups " + s.groups().start() + "–" + s.groups().end() + " (" + s.groups().size() + "), sequences "
                + s.sequences().start() + "–" + s.sequences().end() + " (" + s.sequences().size() + "), MAtricks "
                + s.matricks().start() + "–" + s.matricks().end() + ".");
        out.add("- Executors: page " + s.page() + ", " + s.executors().start() + "–" + s.executors().end()
                + ". A look's `exec` must be in this range; omit `exec` to let the compiler pick the next free one.");
        out.add("- Sequences with an effect that follows the beat run on speed master 3." + s.speedMaster() + " (AutoMA3 sets it to "
                + "the DJ's BPM) unless `\"speed_master\": false`. Static looks and strobes are not linked: strobe presets keep "
                + "their own speed, `strobe` values are in Hz.");
        out.add("- Names must not contain: " + NAME_FORBIDDEN + "\n");

        out.add("## Rig");
        out.add("Frame: x = left→right seen from FOH, y = distance from FOH (grows towards the stage), z = up, mm.\n");
        out.add("| fid | type | caps | x | y | z |");
        out.add("|---|---|---|---|---|---|");
        for (JsonNode f : fixtures) {
            List<String> cells = new ArrayList<>();
            JsonNode p = f.get("pos");
            for (int i = 0; i < 3; i++) cells.add(p != null && p.isArray() ? Py.f0(p.get(i).doubleValue()) : "-");
            out.add("| " + f.get("fid").asText() + " | " + f.get("type").asText() + " | "
                    + orDash(String.join(", ", ShowFiles.texts(f.get("caps")))) + " | " + String.join(" | ", cells) + " |");
        }
        out.add("");

        out.add("## Sets, orderings, mirror pairs");
        JsonNode orderings = rig.path("orderings");
        List<String> orderNames = new ArrayList<>();
        if (orderings.size() > 0) {
            for (String o : ShowFiles.keys(orderings.elements().next())) if (!o.equals("mirror")) orderNames.add("`" + o + "`");
        }
        out.add("Use in a group as `{\"set\": \"<set>\", \"order\": \"<ordering>\"}`. Every set has: " + String.join(", ", orderNames)
                + ". Sets that split fully into mirror pairs also have `mirror`: use it with `wings: 2`.\n");
        Map<Integer, JsonNode> byFid = Rig.fixturesById(rig);
        JsonNode sets = rig.get("sets");
        for (String name : ShowFiles.keys(sets)) {
            List<Integer> fids = ShowFiles.ints(sets.get(name));
            Set<String> common = null;
            for (int f : fids) {
                Set<String> caps = new HashSet<>(ShowFiles.texts(byFid.get(f).get("caps")));
                if (common == null) common = caps;
                else common.retainAll(caps);
            }
            out.add("### `" + name + "`: " + fids.size() + " fixture(s), all have: "
                    + orDash(common == null ? "" : String.join(", ", new TreeSet<>(common))));
            JsonNode o = orderings.path(name);
            if (fids.size() > 1) {
                for (String k : List.of("left_to_right", "foh_to_stage", "center_out", "bottom_to_top", "mirror")) {
                    if (o.has(k)) out.add("- " + k + ": " + Py.repr(ShowFiles.ints(o.get(k))));
                }
            }
            JsonNode pairs = rig.path("pairs").path(name);
            if (pairs.isArray() && !pairs.isEmpty()) out.add("- mirror pairs (outermost first): " + Py.repr(pairs));
            out.add("");
        }

        out.add("## Library (preset keys for `preset`)");
        Map<String, List<String>> groups = new LinkedHashMap<>();
        JsonNode presets = library.get("presets");
        for (String key : ShowFiles.keys(presets)) {
            String cat = String.join("+", ShowFiles.texts(presets.get(key).get("affects")));
            groups.computeIfAbsent(cat.isEmpty() ? "other" : cat, k -> new ArrayList<>()).add(key);
        }
        for (Map.Entry<String, List<String>> e : groups.entrySet()) {
            List<String> keys = e.getValue();
            if (keys.size() > 12) { // the many two-colour phasers: list names only
                out.add("### " + e.getKey() + " (" + keys.size() + ")");
                out.add(String.join(", ", keys.stream().map(k -> "`" + k + "`").toList()) + "\n");
                continue;
            }
            out.add("### " + e.getKey());
            out.add("| key | MA3 | needs | energy | tags |");
            out.add("|---|---|---|---|---|");
            for (String k : keys) {
                JsonNode p = presets.get(k);
                JsonNode en = p.get("energy");
                String energy = en == null || en.isNull() ? "-" : Py.g(en);
                out.add("| `" + k + "` | " + Py.str(p.get("pool")) + "." + Py.str(p.get("index")) + " " + p.get("name").asText() + " | "
                        + String.join(", ", ShowFiles.texts(p.get("requires"))) + " | " + energy + " | "
                        + String.join(", ", ShowFiles.texts(p.get("tags"))) + " |");
            }
            out.add("");
        }
        out.add("### Static values (`values`)");
        JsonNode statics = library.get("static_attributes");
        for (String k : ShowFiles.keys(statics)) {
            JsonNode a = statics.get(k);
            String avail = capsPresent.contains(a.get("cap").asText()) ? "" : "  (no fixture in this rig has it)";
            out.add("- `" + k + "`: " + Py.g(a.get("min")) + "–" + Py.g(a.get("max")) + ", needs " + a.get("cap").asText() + avail);
        }
        out.add("");

        out.add("## Looks to fill: " + looksSource);
        out.add("One plan look per row; copy `automa3_id` (if any) and keep `exec` when it is inside the executor range.\n");
        out.add("| # | automa3_id | name | role | exec | mode | sections | energy | layer |");
        out.add("|---|---|---|---|---|---|---|---|---|");
        List<String> impossible = new ArrayList<>();
        for (int i = 0; i < looks.size(); i++) {
            JsonNode lk = looks.get(i);
            JsonNode m = ma3(lk);
            JsonNode ex = m.get("exec");
            JsonNode page = m.has("page") ? m.get("page") : ShowFiles.JSON.getNodeFactory().numberNode(1);
            String exs;
            if (ex == null || ex.isNull()) exs = "-";
            else if (page.isNumber() && page.doubleValue() == s.page() && ex.isIntegralNumber() && s.executors().contains(ex.asInt())) exs = Py.str(ex);
            else exs = Py.str(page) + "." + Py.str(ex) + " (outside range: omit)";
            String role = lk.has("role") ? Py.str(lk.get("role")) : "";
            String need = PlanValidator.ROLE_NEEDS.get(role.toUpperCase());
            if (need != null && !capsPresent.contains(need)) {
                String label = PlanValidator.truthy(lk.get("name")) ? lk.get("name").asText() : role;
                impossible.add(label + " (" + role + ": no fixture with " + need + ")");
            }
            List<String> sections = ShowFiles.texts(lk.get("sections"));
            out.add("| " + i + " | " + (lk.has("id") ? Py.str(lk.get("id")) : "-") + " | " + (lk.has("name") ? Py.str(lk.get("name")) : "")
                    + " | " + (lk.has("role") ? Py.str(lk.get("role")) : "EFFECT") + " | " + exs + " | "
                    + (PlanValidator.truthy(lk.get("mode")) ? Py.str(lk.get("mode")) : "-") + " | "
                    + (sections.isEmpty() ? "any" : String.join(", ", sections)) + " | " + energy(lk) + " | "
                    + (PlanValidator.truthy(lk.get("layer")) ? Py.str(lk.get("layer")) : "-") + " |");
        }
        out.add("");
        if (!impossible.isEmpty()) {
            out.add("**Cannot be built with this rig** (leave out, mention in `notes`): " + String.join("; ", impossible) + "\n");
        }

        out.add("## Plan schema (authoritative format of plan.json)");
        out.add("```json");
        out.add(ShowFiles.resourceText("schemas/plan.schema.json").stripTrailing());
        out.add("```");
        return String.join("\n", out) + "\n";
    }
}
