package automa3.show;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.security.MessageDigest;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * plan.json (+ rig, library, settings) -> ShowBuilder job (Lua data) + allocation + AutoMA3 look file.
 *
 * <p>The job is a list of generic steps the plugin executes: {op="cmd", cmd=<command line>, fatal=<abort on
 * failure>}, {op="export", addr, file} (read back what was built), {op="list", addr} (log the objects),
 * {op="get", addr, props}, {op="paths"}, {op="patch", ...}, {op="strobe", functions, hz} (a strobe channel function
 * of each selected fixture, in Hz). Every grandMA3 command string comes from
 * {@link BuildProfile}.</p>
 */
public final class ShowCompiler {

    static final String JOB_FORMAT = "ma3sc-job";
    /** Kept from the Python tool: looks built before the move into AutoMA3 carry the same generator name. */
    static final String TOOL = "ma3-showcreator";

    private ShowCompiler() {
    }

    /** A job for the plugin: its steps, in order. */
    public static final class Job {
        public final String kind;
        final BuildProfile profile;
        final List<Map<String, Object>> steps = new ArrayList<>();
        public final List<String> warnings;

        Job(String kind, BuildProfile profile) {
            this.kind = kind;
            this.profile = profile;
            this.warnings = new ArrayList<>(profile.warnings);
        }

        void step(String key, boolean fatal, boolean allowFail, String note, Object... kv) {
            Map<String, Object> step = new LinkedHashMap<>();
            step.put("op", "cmd");
            step.put("cmd", profile.t(key, kv));
            step.put("key", key);
            step.put("fatal", fatal);
            if (allowFail) step.put("allow_fail", true);
            String status = profile.status(key);
            if (!status.equals("manual") && !status.equals("console") && !status.equals("systest")) step.put("unverified", true);
            if (note != null && !note.isEmpty()) step.put("note", note);
            steps.add(step);
        }

        void cmd(String key, Object... kv) {
            step(key, false, false, null, kv);
        }

        void fatal(String key, Object... kv) {
            step(key, true, false, null, kv);
        }

        /** ClearAll, unless the previous step already was one. */
        void clear() {
            if (steps.isEmpty() || !"clear_all".equals(steps.get(steps.size() - 1).get("key"))) cmd("clear_all");
        }

        void op(String op, Object... kv) {
            Map<String, Object> step = new LinkedHashMap<>();
            step.put("op", op);
            for (int i = 0; i + 1 < kv.length; i += 2) step.put((String) kv[i], kv[i + 1]);
            steps.add(step);
        }

        public int stepCount() {
            return steps.size();
        }

        public int unverifiedCount() {
            return (int) steps.stream().filter(s -> Boolean.TRUE.equals(s.get("unverified"))).count();
        }

        List<Map<String, Object>> steps() {
            return steps;
        }

        Map<String, Object> toMap(String ma3Version) {
            String stamp = ZonedDateTime.now(ZoneOffset.UTC).format(DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss'Z'"));
            String hash;
            try {
                byte[] d = MessageDigest.getInstance("SHA-1").digest(LuaWriter.write(steps, 0).getBytes(java.nio.charset.StandardCharsets.UTF_8));
                hash = java.util.HexFormat.of().formatHex(d).substring(0, 8);
            } catch (Exception e) {
                throw new IllegalStateException(e);
            }
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("format", JOB_FORMAT);
            m.put("version", 1);
            m.put("kind", kind);
            m.put("job_id", kind + "-" + stamp + "-" + hash);
            m.put("ma3_version", ma3Version);
            m.put("profile", profile.name);
            m.put("strict_version", true);
            m.put("log_file", "log_" + kind + ".jsonl");
            m.put("export_prefix", "export_" + kind + "_");
            m.put("steps", steps);
            return m;
        }

        public String toLua(String ma3Version) {
            return "-- ShowBuilder job (" + kind + "), generated by " + TOOL + ". Do not edit; recompile instead.\n"
                    + "return " + LuaWriter.write(toMap(ma3Version), 0) + "\n";
        }
    }

    private static void clearRanges(Job job, ShowSettings s) {
        Object[][] ranges = {{"Group", s.groups()}, {"Sequence", s.sequences()}, {"MAtricks", s.matricks()}};
        for (Object[] r : ranges) {
            ShowSettings.Range rng = (ShowSettings.Range) r[1];
            job.step("delete_range", false, true, "fails harmlessly when the range is already empty",
                    "obj", r[0], "start", rng.start(), "end", rng.end());
        }
    }

    /** Pool numbers per key, in plan order: the same plan gives the same numbers. */
    public record Allocation(Map<String, Integer> groups, Map<String, Integer> sequences, Map<String, Integer> executors, int page) {
        ObjectNode toJson() {
            ObjectNode o = ShowFiles.object();
            ObjectNode g = o.putObject("groups");
            groups.forEach(g::put);
            ObjectNode s = o.putObject("sequences");
            sequences.forEach(s::put);
            ObjectNode e = o.putObject("executors");
            executors.forEach(e::put);
            o.put("page", page);
            return o;
        }
    }

    static Allocation allocate(JsonNode plan, ShowSettings s) throws ShowException {
        Map<String, Integer> groups = new LinkedHashMap<>(), seqs = new LinkedHashMap<>(), execs = new LinkedHashMap<>();
        int i = 0;
        for (JsonNode g : plan.get("groups")) groups.put(g.get("key").asText(), s.groups().start() + i++);
        i = 0;
        for (JsonNode q : plan.get("sequences")) seqs.put(q.get("key").asText(), s.sequences().start() + i++);
        Set<Integer> taken = new HashSet<>();
        for (JsonNode lk : plan.get("looks")) if (lk.has("exec")) taken.add(lk.get("exec").asInt());
        int next = s.executors().start();
        for (JsonNode lk : plan.get("looks")) {
            if (lk.has("exec")) {
                execs.put(lk.get("key").asText(), lk.get("exec").asInt());
            } else {
                while (taken.contains(next)) next++;
                if (next > s.executors().end()) throw new ShowException("no free executor left in the reserved range");
                execs.put(lk.get("key").asText(), next++);
            }
        }
        return new Allocation(groups, seqs, execs, s.page());
    }

    private static final String[][] SPREAD_FIELDS = {{"wings", "matricks_wings"}, {"blocks", "matricks_blocks"}, {"groups", "matricks_groups"}};

    /** Identity of a line's MAtricks settings; null when the line has no spread. */
    static String spreadKey(JsonNode line) {
        if (!line.has("phase") && !line.has("wings") && !line.has("blocks") && !line.has("groups")) return null;
        JsonNode ph = line.get("phase");
        return String.join("|", key(line.get("wings")), key(line.get("blocks")), key(line.get("groups")),
                ph == null ? "-" : key(ph.get("from")), ph == null ? "-" : key(ph.get("to")));
    }

    private static String key(JsonNode v) {
        if (v == null) return "-";
        return v.isNumber() ? v.decimalValue().stripTrailingZeros().toPlainString() : ShowFiles.canonical(v);
    }

    /**
     * Plan phase = MAtricks PhaseFromX/PhaseToX semantics: a full 360 cycle spreads as 0,90,180,270 on 4 fixtures
     * (seen on 2.3.2). `At Phase a Thru b` includes both ends (0,120,240,360), so shorten full cycles.
     */
    static double[] atPhaseRange(double lo, double hi, int n) {
        if (n > 1 && Math.abs(hi - lo) == 360) return new double[]{lo, lo + (hi - lo) * (n - 1) / n};
        return new double[]{lo, hi};
    }

    /**
     * Programmer method: select the group, MAtricks grid settings, preset/values, then the phase. groupFunctions:
     * the channel functions the group's fixtures have (for values like strobe that use whichever one exists).
     */
    private static void applyLine(Job job, JsonNode library, JsonNode line, int groupNo, int nFixtures, java.util.Set<String> groupFunctions) {
        job.cmd("matricks_reset");
        job.fatal("select_group", "no", groupNo);
        for (String[] f : SPREAD_FIELDS) {
            if (line.has(f[0])) job.cmd("matricks_set", "prop", job.profile.t(f[1]), "value", Py.str(line.get(f[0])));
        }
        if (line.has("preset")) {
            JsonNode p = library.get("presets").get(line.get("preset").asText());
            job.fatal("at_preset", "pool", Py.str(p.get("pool")), "index", Py.str(p.get("index")));
        } else {
            for (String a : ShowFiles.keys(line.get("values"))) {
                JsonNode st = library.get("static_attributes").get(a);
                if (st.has("functions")) {
                    // channel functions cannot be addressed on the command line (`Attribute "Shutter1Strobe" At 12`
                    // fails, `At N` is a percent of whichever function the channel is in); the plugin sets each
                    // selected fixture's own strobe function in Hz (observed on onPC 2.3.2)
                    List<String> fns = new ArrayList<>();
                    for (JsonNode f : st.get("functions")) if (groupFunctions.contains(f.asText())) fns.add(f.asText());
                    if (!fns.isEmpty()) job.op("strobe", "key", "strobe_hz", "functions", fns, "hz", line.get("values").get(a).doubleValue(), "fatal", true);
                } else {
                    job.fatal("at_attribute", "attr", st.get("ma3").asText(), "value", Py.num(line.get("values").get(a)));
                }
            }
        }
        if (line.has("phase")) { // needs the phaser steps in the programmer first
            double[] r = atPhaseRange(line.get("phase").get("from").doubleValue(), line.get("phase").get("to").doubleValue(), nFixtures);
            job.cmd("at_phase", "lo", Py.num(r[0]), "hi", Py.num(r[1]));
        }
    }

    /** Creates one MAtricks pool object per distinct spread and reuses it. */
    private static final class MatricksPool {
        private final Job job;
        private int next;
        private final Map<String, Integer> made = new HashMap<>();

        MatricksPool(Job job, ShowSettings s) {
            this.job = job;
            this.next = s.matricks().start();
        }

        int get(JsonNode line, int groupNo) {
            String key = spreadKey(line);
            if (made.containsKey(key)) return made.get(key);
            int no = next++;
            job.clear();
            job.cmd("matricks_reset");
            job.cmd("select_group", "no", groupNo);
            List<String> label = new ArrayList<>();
            for (String[] f : SPREAD_FIELDS) {
                if (line.has(f[0])) {
                    job.cmd("matricks_set", "prop", job.profile.t(f[1]), "value", Py.str(line.get(f[0])));
                    label.add(f[0].charAt(0) + Py.str(line.get(f[0])));
                }
            }
            if (line.has("phase")) {
                String lo = Py.num(line.get("phase").get("from")), hi = Py.num(line.get("phase").get("to"));
                job.cmd("matricks_set", "prop", job.profile.t("matricks_phase_from"), "value", lo);
                job.cmd("matricks_set", "prop", job.profile.t("matricks_phase_to"), "value", hi);
                label.add(0, "ph" + lo + "-" + hi);
            }
            job.fatal("store_matricks", "no", no);
            job.cmd("label", "obj", "MAtricks", "no", no, "name", ("SC " + String.join(" ", label)).replace(".", "p"));
            job.cmd("matricks_reset");
            job.clear();
            made.put(key, no);
            return no;
        }
    }

    static final List<String> SEQUENCE_READBACK = List.of("Name", "SpeedMaster", "SpeedScale", "Priority", "OffWhenOverridden");

    public record Compiled(Job job, Allocation allocation, ObjectNode looks) {
    }

    /** Assumes the plan passed validation. looksIn: the AutoMA3 look list the plan was made for (may be empty). */
    static Compiled compileBuild(JsonNode plan, JsonNode rig, JsonNode library, ShowSettings s, List<JsonNode> looksIn) throws ShowException {
        BuildProfile profile = BuildProfile.resolve(s.ma3Version(), s.commandOverrides());
        Job job = new Job("build", profile);
        Allocation alloc = allocate(plan, s);
        MatricksPool matricks = new MatricksPool(job, s);

        job.clear();
        clearRanges(job, s);

        Map<String, Integer> groupSize = new HashMap<>();
        Map<String, java.util.Set<String>> groupFunctions = new HashMap<>();
        Map<Integer, JsonNode> byFid = Rig.fixturesById(rig);
        for (JsonNode g : plan.get("groups")) {
            int no = alloc.groups().get(g.get("key").asText());
            List<Integer> fids = Rig.resolveGroup(rig, g.get("fixtures"));
            groupSize.put(g.get("key").asText(), fids.size());
            java.util.Set<String> fn = new HashSet<>();
            for (int f : fids) if (byFid.containsKey(f)) fn.addAll(ShowFiles.texts(byFid.get(f).get("functions")));
            groupFunctions.put(g.get("key").asText(), fn);
            job.clear();
            List<String> ids = fids.stream().map(String::valueOf).toList();
            job.fatal("select_fixtures", "fids", String.join(profile.t("fid_join"), ids));
            job.fatal("store_group", "no", no);
            job.cmd("label", "obj", "Group", "no", no, "name", g.get("name").asText());
        }
        job.clear();

        boolean recipe = "recipe".equals(s.cueMethod());
        for (JsonNode sq : plan.get("sequences")) {
            int seq = alloc.sequences().get(sq.get("key").asText());
            boolean cooked = false;
            JsonNode cues = sq.get("cues");
            for (int ci = 1; ci <= cues.size(); ci++) {
                JsonNode cue = cues.get(ci - 1);
                List<JsonNode> recipeLines = new ArrayList<>();
                if (recipe) for (JsonNode l : cue.get("lines")) if (l.has("preset")) recipeLines.add(l);
                // programmer part: static values (and, with cue_method=programmer, presets too)
                job.clear();
                for (JsonNode line : cue.get("lines")) {
                    if (!containsEqual(recipeLines, line)) {
                        String gk = line.get("group").asText();
                        applyLine(job, library, line, alloc.groups().get(gk), groupSize.get(gk), groupFunctions.get(gk));
                    }
                }
                job.fatal("store_cue", "seq", seq, "cue", ci);
                job.cmd("matricks_reset");
                job.clear();
                // recipe part: one recipe line per preset line, cooked once per sequence below
                for (int n = 1; n <= recipeLines.size(); n++) {
                    JsonNode line = recipeLines.get(n - 1);
                    JsonNode p = library.get("presets").get(line.get("preset").asText());
                    int gno = alloc.groups().get(line.get("group").asText());
                    Integer m = spreadKey(line) != null ? matricks.get(line, gno) : null;
                    job.fatal("recipe_assign", "obj", "Group", "no", gno, "seq", seq, "cue", ci, "line", n);
                    job.fatal("recipe_assign", "obj", "Preset", "no", Py.str(p.get("pool")) + "." + Py.str(p.get("index")),
                            "seq", seq, "cue", ci, "line", n);
                    if (m != null) job.fatal("recipe_assign", "obj", "MAtricks", "no", m, "seq", seq, "cue", ci, "line", n);
                    cooked = true;
                }
                if (cue.has("fade")) job.cmd("cue_fade", "seq", seq, "cue", ci, "fade", Py.num(cue.get("fade")));
            }
            if (cooked) job.fatal("cook_sequence", "seq", seq);
            for (int ci = 1; ci <= cues.size(); ci++) { // after cooking: cooking may rename cues after the preset
                job.cmd("label_cue", "seq", seq, "cue", ci, "name", cues.get(ci - 1).get("name").asText());
            }
            job.cmd("label", "obj", "Sequence", "no", seq, "name", sq.get("name").asText());
            boolean onBpm = onSpeedMaster(sq, library);
            if (onBpm) job.cmd("speed_master", "seq", seq, "master", s.speedMaster());
            // layers: a look must not switch itself off when another layer overrides all its values
            job.cmd("seq_prop", "seq", seq, "prop", "OffWhenOverridden", "value", "No");
            String scale = sq.path("speed_scale").asText("One");
            if (onBpm && !scale.equals("One")) job.cmd("seq_prop", "seq", seq, "prop", "SpeedScale", "value", scale);
            if (sq.has("priority")) job.cmd("seq_prop", "seq", seq, "prop", "Priority", "value", sq.get("priority").asText());
        }

        for (JsonNode lk : plan.get("looks")) {
            job.fatal("assign_exec", "seq", alloc.sequences().get(lk.get("sequence").asText()), "page", s.page(),
                    "exec", alloc.executors().get(lk.get("key").asText()));
        }
        job.clear();

        // read back what was built, for verification from disk
        for (JsonNode sq : plan.get("sequences")) {
            int no = alloc.sequences().get(sq.get("key").asText());
            job.op("get", "addr", "Sequence " + no, "props", SEQUENCE_READBACK);
            job.op("export", "addr", "Sequence " + no, "file", "sequence_" + no + ".xml");
        }
        for (JsonNode g : plan.get("groups")) {
            int no = alloc.groups().get(g.get("key").asText());
            job.op("export", "addr", "Group " + no, "file", "group_" + no + ".xml");
        }
        return new Compiled(job, alloc, looksFile(plan, alloc, s, looksIn == null ? List.of() : looksIn));
    }

    /**
     * Whether a sequence follows the BPM speed master: as the plan says, else only when it runs an effect that
     * follows the beat. Static looks have nothing to time, and strobe phasers keep their own speed (grandMA3's
     * "Strobe" runs at 10 Hz; linked to the speed master it would flash once per beat).
     */
    static boolean onSpeedMaster(JsonNode sq, JsonNode library) {
        if (sq.has("speed_master")) return sq.get("speed_master").asBoolean(true);
        return beatPhasers(sq, library) > 0;
    }

    /** Effect lines of a sequence that follow the beat (phasers that are not strobes). */
    static int beatPhasers(JsonNode sq, JsonNode library) {
        int n = 0;
        for (JsonNode c : sq.path("cues")) {
            for (JsonNode l : c.path("lines")) {
                JsonNode p = library.path("presets").get(l.path("preset").asText(""));
                if (p != null && "phaser".equals(p.path("kind").asText()) && !isStrobe(p)) n++;
            }
        }
        return n;
    }

    static boolean isStrobe(JsonNode preset) {
        return ShowFiles.texts(preset.get("tags")).contains("strobe");
    }

    /** Python's {@code line not in recipe_lines}: equality by value. */
    private static boolean containsEqual(List<JsonNode> list, JsonNode v) {
        for (JsonNode x : list) if (x.equals(v)) return true;
        return false;
    }

    /**
     * Looks of the AutoMA3 list the plan did not fill (e.g. Haze without a hazer): written back disabled, so AutoMA3
     * does not fire an executor the build left empty.
     */
    private static List<ObjectNode> disabledLeftovers(JsonNode plan, Allocation alloc, ShowSettings s, List<JsonNode> looksIn) {
        Set<String> ids = new HashSet<>();
        for (JsonNode lk : plan.get("looks")) ids.add(lk.has("automa3_id") ? ShowFiles.canonical(lk.get("automa3_id")) : "null");
        Set<Integer> execs = new HashSet<>(alloc.executors().values());
        List<ObjectNode> out = new ArrayList<>();
        for (JsonNode lk : looksIn) {
            JsonNode m = lk.path("ma3").isObject() ? lk.get("ma3") : ShowFiles.object();
            JsonNode page = m.has("page") ? m.get("page") : (lk.has("page") ? lk.get("page") : ShowFiles.JSON.getNodeFactory().numberNode(1));
            JsonNode ex = m.has("exec") ? m.get("exec") : lk.get("exec");
            boolean hasId = PlanValidator.truthy(lk.get("id"));
            boolean onPage = page.isNumber() && page.doubleValue() == s.page();
            boolean execBuilt = ex != null && ex.isNumber() && ex.doubleValue() == Math.rint(ex.doubleValue())
                    && execs.contains((int) ex.doubleValue());
            if ((hasId && ids.contains(ShowFiles.canonical(lk.get("id")))) || (onPage && execBuilt)) continue;
            ObjectNode entry = ShowFiles.object();
            entry.set("name", lk.has("name") ? lk.get("name").deepCopy() : ShowFiles.JSON.getNodeFactory().textNode(""));
            entry.put("disableOnly", true); // only switches off a matching look on import, never adds one
            entry.set("role", lk.has("role") ? lk.get("role").deepCopy() : ShowFiles.JSON.getNodeFactory().textNode("EFFECT"));
            entry.put("enabled", false);
            ObjectNode ma3 = entry.putObject("ma3");
            ma3.set("page", page.deepCopy());
            ma3.set("exec", ex == null ? null : ex.deepCopy());
            entry.putObject("meta").putObject("generator").put("tool", TOOL).put("note", "not built by the plan (see plan notes)");
            if (hasId) entry.set("id", lk.get("id").deepCopy());
            out.add(entry);
        }
        return out;
    }

    /** AutoMA3 look file (format automa3-looks v1) for the generated executors. Only fields the plan sets. */
    static ObjectNode looksFile(JsonNode plan, Allocation alloc, ShowSettings s, List<JsonNode> looksIn) {
        ArrayNode looks = ShowFiles.array();
        for (JsonNode lk : plan.get("looks")) {
            ObjectNode out = looks.addObject();
            String key = lk.get("key").asText();
            out.put("id", PlanValidator.truthy(lk.get("automa3_id")) ? lk.get("automa3_id").asText() : "sc_" + key);
            out.put("name", lk.get("name").asText());
            out.put("role", lk.get("role").asText());
            out.putObject("ma3").put("page", s.page()).put("exec", alloc.executors().get(key))
                    .put("sequence", alloc.sequences().get(lk.get("sequence").asText()));
            for (String k : List.of("description", "layer", "mode", "sections", "energy", "weight", "flashBeats", "level", "tags")) {
                if (lk.has(k)) out.set(k, lk.get(k).deepCopy());
            }
            out.put("enabled", true);
            out.putObject("meta").putObject("generator").put("tool", TOOL).put("look", key).put("sequence", lk.get("sequence").asText());
        }
        disabledLeftovers(plan, alloc, s, looksIn).forEach(looks::add);
        ObjectNode file = ShowFiles.object();
        file.put("format", "automa3-looks").put("version", 1).put("exportedBy", TOOL)
                .put("exportedAt", ZonedDateTime.now(ZoneOffset.UTC).format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'")));
        file.putObject("context").put("speedMaster", s.speedMaster());
        file.set("looks", looks);
        return file;
    }

    /** Changes nothing on the console: logs paths, Cmd() feedback strings and what is in the reserved ranges. */
    static Job compileInspect(ShowSettings s) throws ShowException {
        Job job = new Job("inspect", BuildProfile.resolve(s.ma3Version(), s.commandOverrides()));
        job.op("paths");
        job.op("cmd", "cmd", "ShowCreatorSyntaxProbe", "fatal", false, "allow_fail", true, "note", "deliberately invalid: logs the error feedback text");
        Object[][] ranges = {{"Group", s.groups()}, {"Sequence", s.sequences()}, {"MAtricks", s.matricks()}};
        for (Object[] r : ranges) {
            ShowSettings.Range rng = (ShowSettings.Range) r[1];
            job.op("list", "addr", r[0] + " " + rng.start() + " Thru " + rng.end());
        }
        // ObjectList("Page 1.101 Thru 1.199") crashed the Lua engine on 2.3.2 (uncatchable): executors are not listed.
        job.op("list", "addr", "Preset 21.1 Thru 21.200");
        job.op("list", "addr", "Fixture 1 Thru 9999", "note", "last: riskiest address");
        return job;
    }

    /**
     * Phaser-in-cue experiments at the END of the reserved ranges, results exported as XML.
     * A: programmer + At Phase -> Sequence end-2; B: programmer + MAtricks phase -> end-1; C: recipe line + MAtricks -> end.
     */
    static Job compileProbe(List<Integer> fids, JsonNode library, ShowSettings s) throws ShowException {
        BuildProfile profile = BuildProfile.resolve(s.ma3Version(), s.commandOverrides());
        Job job = new Job("probe", profile);
        JsonNode chase = library.get("presets").get("chase");
        String pool = Py.str(chase.get("pool")), index = Py.str(chase.get("index"));
        int g = s.groups().end(), m = s.matricks().end();
        int sa = s.sequences().end() - 2, sb = s.sequences().end() - 1, sc = s.sequences().end();
        String fidList = String.join(profile.t("fid_join"), fids.stream().map(String::valueOf).toList());

        // inspect listed 0 objects for "Preset 21.1 Thru 21.200": empty pool or unsupported address form?
        job.op("list", "addr", "Preset " + pool + "." + index);
        job.op("list", "addr", "Preset 21.1 Thru 21.10");
        job.clear();
        Object[][] del = {{"Group", g}, {"Sequence", sa}, {"Sequence", sb}, {"Sequence", sc}, {"MAtricks", m}};
        for (Object[] d : del) job.step("delete_range", false, true, null, "obj", d[0], "start", d[1], "end", d[1]);
        job.fatal("select_fixtures", "fids", fidList);
        job.fatal("store_group", "no", g);
        job.cmd("label", "obj", "Group", "no", g, "name", "SC probe");
        // A
        job.clear();
        job.cmd("select_group", "no", g);
        job.cmd("at_preset", "pool", pool, "index", index);
        job.cmd("at_phase", "lo", 0, "hi", 360);
        job.cmd("store_cue", "seq", sa, "cue", 1);
        job.cmd("label", "obj", "Sequence", "no", sa, "name", "SC probe A AtPhase");
        // B
        job.clear();
        job.cmd("select_group", "no", g);
        job.cmd("matricks_set", "prop", profile.t("matricks_phase_from"), "value", 0);
        job.cmd("matricks_set", "prop", profile.t("matricks_phase_to"), "value", 360);
        job.cmd("at_preset", "pool", pool, "index", index);
        job.cmd("store_cue", "seq", sb, "cue", 1);
        job.cmd("label", "obj", "Sequence", "no", sb, "name", "SC probe B MAtricks");
        job.cmd("matricks_reset");
        // C
        job.clear();
        job.cmd("select_group", "no", g);
        job.cmd("matricks_set", "prop", profile.t("matricks_phase_from"), "value", 0);
        job.cmd("matricks_set", "prop", profile.t("matricks_phase_to"), "value", 360);
        job.cmd("store_matricks", "no", m);
        job.cmd("matricks_reset");
        job.clear();
        job.step("store_cue", false, false, "empty cue for the recipe", "seq", sc, "cue", 1);
        job.cmd("recipe_assign", "obj", "Group", "no", g, "seq", sc, "cue", 1, "line", 1);
        job.cmd("recipe_assign", "obj", "Preset", "no", pool + "." + index, "seq", sc, "cue", 1, "line", 1);
        job.cmd("recipe_assign", "obj", "MAtricks", "no", m, "seq", sc, "cue", 1, "line", 1);
        job.cmd("cook_sequence", "seq", sc);
        job.cmd("label", "obj", "Sequence", "no", sc, "name", "SC probe C Recipe");
        job.clear();

        // speed master: property "SpeedMaster" (sequence_settings.uixml), value format unknown -> try variants
        int sm = s.speedMaster();
        Object[][] variants = {{sa, "Speed" + sm}, {sb, "3." + sm}, {sc, "Master 3." + sm}};
        for (Object[] v : variants) {
            job.op("cmd", "cmd", "Set Sequence " + v[0] + " Property \"SpeedMaster\" \"" + v[1] + "\"", "fatal", false,
                    "allow_fail", true, "note", "speed master experiment");
        }
        for (int no : new int[]{sa, sb, sc}) job.op("get", "addr", "Sequence " + no, "props", List.of("SpeedMaster", "Name"));
        for (int no : new int[]{sa, sb, sc}) job.op("export", "addr", "Sequence " + no, "file", "sequence_" + no + ".xml");
        job.op("export", "addr", "MAtricks " + m, "file", "matricks_" + m + ".xml");
        job.op("export", "addr", "Group " + g, "file", "group_" + g + ".xml");
        job.op("export", "addr", "Preset " + pool + "." + index, "file", "preset_chase.xml");
        return job;
    }

    static final List<String> FIXTURE_PROPS = List.of("FID", "CID", "Name", "PosX", "PosY", "PosZ", "RotX", "RotY", "RotZ", "Layer", "Class");

    /** Reads the patch from the show (changes nothing): fixture types as XML, fixtures with type/mode/position. */
    static Job compilePatch(ShowSettings s) throws ShowException {
        Job job = new Job("patch", BuildProfile.resolve(s.ma3Version(), s.commandOverrides()));
        job.op("patch", "fixtures", "Fixture 1 Thru 9999", "props", FIXTURE_PROPS);
        return job;
    }

    static List<JsonNode> list(JsonNode array) {
        List<JsonNode> out = new ArrayList<>();
        if (array != null) {
            Iterator<JsonNode> it = array.elements();
            while (it.hasNext()) out.add(it.next());
        }
        return out;
    }
}
